### ISSUE TITLE
Arduino Pro Micro?

### ISSUE THREAD

**Issue by opthomas-prime** [xelalexv/suniversal#3]
More like a question, i'm sorry for that: I can't find a "Pro Micro" in the Arduino product line. Can you give me a pointer on that?

**Comment by xelalexv** [comment]
Corrected README.

**Comment by opthomas-prime** [comment]
Thanks for the clarification @xelalexv 
I can confirm now that the Arduino Micro works!
Good job on that project - felt like Plug & Play :smile:

**Comment by xelalexv** [comment]
Glad to hear it's working. I'll add a list to the readme with boards confirmed working. Have fun hacking on the Sun keyboard!
